### ISSUE TITLE
Pleroma instance identification problem

### ISSUE THREAD

**Issue by bugsysop** [mkljczk/pl-fe#117]
My Pleroma instance (2.6.2) is not correctly identified as such, and is confused with Mastodon. The publication options offered are therefore reduced (text length limited to 500 characters, for example).

Note tested with demo of PE-FE (https://pl.mkljczk.pl/)

**Comment by mkljczk** [comment]
Checked social.tmprs.net without sign in. It is detected as Pleroma 2.6.2 and the feature set seems to be inferred correctly
![obraz](https://github.com/user-attachments/assets/10274f2b-d1c7-4655-b314-fb566344e45d)

**Comment by mkljczk** [comment]
Ok, I see where this comes from, made a mistake related to /v1/instance schema conversion, I'll fix this

**Comment by mkljczk** [comment]
Should be fixed now

**Comment by bugsysop** [comment]
Working fine! Thanks a lot.
