### ISSUE TITLE
Admin Dashboard messup

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#126]
Since i checked out
- PL-FE https://github.com/mkljczk/pl-fe/commit/f5e70128c84d6af04d6cd5855b3c18e3a0d4cb74 
- PL https://github.com/mkljczk/pl/commit/2cdc1985a5e3533515cd468d9b4916c086c92e57

### Issues 

I have no more administrative privileges in Admin Dashboard

![Screenshot 2024-10-19 at 00-26-11 Cruscotto](https://github.com/user-attachments/assets/97b1b7ab-c2b1-405b-a4a5-35a476dfc8bb)

Dashboard itself thinks I've installed Mastodon 0

![immagine](https://github.com/user-attachments/assets/0ca2f7fd-7c7f-4a41-b263-4309903c1d0c)

- Subscription are disabled :(
- Visiting in a new session, theme is lost. It's default Pink.

I think it's happening because PL-FE thinks to be connected to unknown Mastodon. 
How can I set correct PL version number? Or pleroma number?
@mkljczk please, can you tell me something asap? Actually our instance is semi messed up

**Comment by tassoman** [comment]
Server's JSON API tells: `{ "version": "2.7.2 (compatible; Pleroma 2.7.0-0-g2cdc1985a.fork+pl)"`
Maybe string is unparsable by pl-fe ?

**Comment by mkljczk** [comment]
should be fixed by 5befd8e9dbcf96e68d2c1d441d08e0760722507b
