### ISSUE TITLE
[Bug] Broken teeth for bites

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#127]
Can't bite anyone, since https://github.com/mkljczk/pl-fe/commit/5befd8e9dbcf96e68d2c1d441d08e0760722507b

Effect: toast message error.

**Comment by mkljczk** [comment]
This is a backend issue, I have a branch with the fix, will merge it today. I think some stuff related to events might be broken as well

**Comment by tassoman** [comment]
Didn't tried event publishing yet. Let me see.

**Comment by tassoman** [comment]
@mkljczk Correct, can't even publish an event.

**Comment by mkljczk** [comment]
should be fixed now
