### ISSUE TITLE
[Bug] status wiped when attachment have no ALT

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#138]
When you try to post something having an attachment without description, confirmation modal (about alt text) wipes status text.

Condition: having settings "confirm posting without ALT text" turned on.

### Steps

1. write: status text inside compositor
2. attach: an image without description
3. click: post
4. see: text gets wiped out just before modal rendering
5. A) click: modal's post. it will send empty text with attachment having empty alt
6. B) click: modal's cancel. nothing happens
7. C) click: outside modal box, you return at composition but text got wiped out

**Comment by mkljczk** [comment]
should be fixed by b9475efdec

**Comment by tassoman** [comment]
Confirmed, thankzx!
