### ISSUE TITLE
Direct published post edition

### ISSUE THREAD

**Issue by bugsysop** [mkljczk/pl-fe#156]
I don’t know if is a bug, a choice or a missing functionality, but actually it’s not possible to direct edit a published post (like in Soapbox or Pleroma-FR), you have to delete and republish... Mastodon old style.

Note: I’m using Pleroma (not a fork)

**Comment by mkljczk** [comment]
Should be fixed by 6a9921a409, thanks

**Comment by bugsysop** [comment]
Thanks!
