### ISSUE TITLE
PL-FE: dosn't generate backup

### ISSUE THREAD

**Issue by bugsysop** [mkljczk/pl-fe#157]
When asking for an _account backup_, nothing occurs. When you try a second time, you have an error message that say you generate a backup _“less than 7 days ago”_.

Using: 
- PL-FE demo instance.
- Pleroma (unmodified)

**Comment by bugsysop** [comment]
Tested with Soapbox this was working fine.

**Comment by mkljczk** [comment]
Should be fine now, thanks
