### ISSUE TITLE
Global configuration access link

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#50]
As Administrator I'd like to see a global configuration link, so that I can access `pl-fe/config`

### Description

I had to guess config url was pl-fe/config because of soapbox fork. 
Maybe it's useful to add a link inside "others" under conditional check "profile is admin".
Maybe link name could be "Global configuration" or "Server configuration".

**Comment by mkljczk** [comment]
It is linked in the dashboard
