### ISSUE TITLE
Profile settings are not automatically loaded

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#52]
As user, I want profile settings and UI/UX changes effective as they are stored/changed

### Description

I changed default posting privacy (default: followers) then opened home timeline. 
Composition window still had previous settings (default: public).
CTRL+R page reload was needed to apply new settings.

Proposed solution: just reload entire the page when saving settings (now are saved on field change. No save button)

**Comment by mkljczk** [comment]
It gets applied immediately after saving the settings, but only if you haven't started composing a post before changing the settings

**Comment by tassoman** [comment]
Well, yes confirmed. 
It's weird, to understand because composition block looks like it's a physical part of the UI. 
But, in reality it's a "not existing" message item who gets attributes just when edited. 
Publish button and word count turns 100%. But doesn't happens to action buttons and upper side select buttons neither. 
UX should be homogeneous, so that, also select buttons inside the composition pane should start faded, then go to 100% just editing. 🤔
