### ISSUE TITLE
Set up Weblate or some other translation management service

### ISSUE THREAD

**Issue by mkljczk** [mkljczk/pl-fe#54]

**Comment by tassoman** [comment]
I made the effort for Soapbox, I can work also on this if you're interested :thinking:

**Comment by mkljczk** [comment]
<a href="https://hosted.weblate.org/engage/pl-fe/">
<img src="https://hosted.weblate.org/widget/pl-fe/pl-fe/open-graph.png" alt="Translation status" />
</a>
https://hosted.weblate.org/projects/pl-fe/pl-fe/

**Comment by tassoman** [comment]
Remember to avoid strings insertion or deletion in every language different from en.json. Usually breaks pull request syncro. 
A solution can be configuring weblate pushing to a branch you need to merge manually.
Also should be documented into project README file
