### ISSUE TITLE
Can't create Bookmarks folder

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#64]
By running PL as backend, pl-fe shows me ability to bookmark posts in folder.
While clicking on "create folder", inside bookmarks folder selection modal window, nothing happens.
Are bookmarks storable in directories? Only Mastodonts?  😕

**Comment by mkljczk** [comment]
It appears after refreshing. I'll try to debug this. Thanks

Mastodon doesn't have this feature.

**Comment by tassoman** [comment]
UI/UX hinting:

Remove "Add bookmark" from status menu. Move it as an "official" button. 
Pushing the button, saves the bookmark. If there are categories, popups modal to choose category. 
Touching any item from the list closes the modal and eventually updates.
Touching toast message stills the same.
Button add category should await for result. Category list is the result to pass as prop to category list component, so it can grow up.
Modal only close touching any radio item of the list, even if already selected.

**Comment by mkljczk** [comment]
fixed by de1d147cbd
