### ISSUE TITLE
Attachment selection on Safari iOS opens "Files" activity instead of "Gallery" image selection activity

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#78]
User said: when you choose an attachment, you can upload any file on Android and PC, so file selection starts.
On iOS files are stored differently from gallery. You can't choose images in file and viceversa.
Gallery can store images and videos.
I haven't any iOS device to test this.

**Comment by mkljczk** [comment]
Is this actually true? If a website allows uploading files in arbitrary, you can’t upload an image?

I’ll test this with BrowserStack soon

**Comment by tassoman** [comment]
Tested confirmed seen with my own witness eyes 👀 on friend's device. 
Maybe we can have 📎 button opening a two items menu list.

- Attach media
- Upload file

Then allow only media filetypes in the first situation (I guess will open iOS gallery). And allow only cute files in the second situation (doc*, xls*, pdf, od*) no zip or other archives.

Last choice, maybe we can simply get rid of general file upload. Only spammers and phishers are randomly sending PDFs.
(Edit: Well... Also general documents have Macroes, javascript and python lately, altough softwares are configured to safely ignore them)

**Comment by mkljczk** [comment]
I often use file upload to send Pleroma patches to other users, so I have no plans to remove arbitrary file format upload.

**Comment by tassoman** [comment]
See: https://github.com/mkljczk/pl-fe/pull/91#issuecomment-2364641256

**Comment by mkljczk** [comment]
Ok, I couldn't believe iOS actually prevents uploading both types of files. Fixed by 9096fdc9fbf705b9352a6ebf2498540ebef9dbfd.

![](https://github.com/user-attachments/assets/78293765-5300-45b4-aeb8-76e5b9f3eee6)

**Comment by tassoman** [comment]
It's iOS not free software :wink:
