### ISSUE TITLE
"Mark Status as sensitive" menu item is not working

### ISSUE THREAD

**Issue by tassoman** [mkljczk/pl-fe#84]
As Moderator, as Administrator, I want to set any federated status as sensitive so that users are not directly exposed to such kind of publications.

### Description

We have option to mark sensitive Statuses but is not working. Although modal window asks for confirmation status stills not sensitive, after a full page reload also.

**Comment by mkljczk** [comment]
fixed by 6c5b30e7205e4e76de3c0025ca2edee77de8a54c
